### ISSUE TITLE
Mouse events insted interval 

### ISSUE THREAD

**Issue by vuxor** [nlukic97/zadatak_7#2]
https://github.com/nlukic97/zadatak_7/blob/fa4a768b601a5bacc84d6edc307718c76d996bd6/public/js/script.js#L21

Why don't you use onmouseenter and onmouseleave event listeners for video container instead of interval?

**Comment by nlukic97** [comment]
Hey @vuxor ! I did this on purpose to make a 2 second delay between the moment the user stops moving the cursor over the video and the moment control bar disappears (similar to the behavior on Youtube in fullscreen mode)

**Comment by vuxor** [comment]
In that case you can just add timeout for hiding the controls when mouse leave.

**Comment by nlukic97** [comment]
Yes, of course. This should address the issue.
https://github.com/nlukic97/zadatak_7/pull/3/commits/733a8793781f9445ea8e4a8b0e6fe21ff74f704b

Awaiting for your confirmation before I merge to master.
